INSERT INTO COUNTRY (CODE, NAME) VALUES ('ESP', 'Espanya');
INSERT INTO COUNTRY (CODE, NAME) VALUES ('ITA', 'Italia');
INSERT INTO COUNTRY (CODE, NAME) VALUES ('JPN', 'Japon');

INSERT INTO CONFLICT (NAME, START_DATE, STATUS, DESCRIPTION) VALUES ('Guerra Espanya', '2026-02-20', 'ACTIVE', 'Guerra activa degut a la invasio de italia a espanya');

INSERT INTO EVENT (EVENT_DATE, DESCRIPTION, LOCATION, CONFLICT_ID) VALUES ('2026-02-20', 'Guerra activa degut a la invasio de italia a espanya', 'Espanya i Italia', 1);

INSERT INTO FACTION (NAME, CONFLICT_ID) VALUES ('Espanya', 1);
INSERT INTO FACTION (NAME, CONFLICT_ID) VALUES ('Italia', 1);
INSERT INTO CONFLICT_COUNTRY (CONFLICT_ID, COUNTRY_ID) VALUES (1, 1);
INSERT INTO CONFLICT_COUNTRY (CONFLICT_ID, COUNTRY_ID) VALUES (1, 2);